# Generated by Django 5.1.4 on 2026-07-01 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Reçue"),
                            ("processing", "En cours"),
                            ("completed", "Terminée"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("response_at", models.DateTimeField(blank=True, null=True)),
                (
                    "export_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 (hex) du fichier exporté — preuve d'intégrité.",
                        max_length=64,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("json", "JSON"), ("csv", "CSV (archive ZIP)")],
                        default="json",
                        max_length=10,
                    ),
                ),
                ("request_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande d'export RGPD",
                "verbose_name_plural": "Demandes d'export RGPD",
                "ordering": ["-requested_at"],
            },
        ),
    ]
